# Generated by Django 2.2.24 on 2022-01-21 04:15

import django.core.validators
from django.db import migrations, models

import judge.models.problem_data
import judge.utils.problem_data


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0196_ultimate_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='batch_type',
            field=models.CharField(choices=[('sum', 'Sum'), ('min', 'Min')], default='min', max_length=10, verbose_name='Batch Type', help_text='Determines how batch scoring is calculated.'),
        ),
    ]
