# Generated by Django 2.2.24 on 2022-01-21 04:15

import django.core.validators
from django.db import migrations, models
from django.core.validators import RegexValidator

import judge.models.problem_data
import judge.utils.problem_data


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0197_min_and_sum_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestproblem',
            name='hidden_subtasks',
            field=models.CharField(
                max_length=20,
                blank=True,
                default="",
                help_text='Separated by commas, e.g: 2, 3',
                verbose_name='hidden subtasks',
                validators=[
                    RegexValidator(
                        regex=r'^\d+(,\d+)*$',
                        message='Only numbers separated by commas are allowed, e.g., "2,3,5".',
                        code='invalid_hidden_subtasks'
                    )
                ]
            )
        ),
    ]
