# Generated by Django 2.2.24 on 2022-01-21 04:15

import django.core.validators
from django.db import migrations, models
from django.core.validators import RegexValidator

import judge.models.problem_data
import judge.utils.problem_data


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0198_hidden_subtasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='has_hidden_subtasks',
            field=models.BooleanField(default=False, help_text='Enable hidden subtasks for this contest.', verbose_name='Has hidden subtasks'),
        ),
    ]
