# Generated by Django 3.2.25 on 2025-04-09 12:57

import django.core.validators
from django.db import migrations, models
import judge.models.problem


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0199_hidden_subtasks_fill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestproblem',
            name='hidden_subtasks',
            field=models.CharField(blank=True, default='0', help_text='Separated by commas, e.g: 2, 3', max_length=200, null=True, verbose_name='hidden subtasks'),
        ),
    ]
