# Generated by Django 2.2.24 on 2022-01-21 04:15

import django.core.validators
from django.db import migrations, models
from django.core.validators import RegexValidator

import judge.models.problem_data
import judge.utils.problem_data


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0200_auto_20250409_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='show_number_of_submission',
            field=models.BooleanField(default=False, help_text='Show number of submission column.', verbose_name='Show number of submission'),
        ),
    ]
