# Generated by Django 2.2.24 on 2022-01-21 04:15

import django.core.validators
from django.db import migrations, models
from django.core.validators import RegexValidator

import judge.models.problem_data
import judge.utils.problem_data


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0201_show_number_of_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='offline_mode',
            field=models.BooleanField(default=False, help_text='Enable offline mode for this contest. Remember to setup hidden subtasks.', verbose_name='Offline mode'),
        ),
    ]
