# Generated by Django 2.2.24 on 2022-01-21 04:15

import django.core.validators
from django.db import migrations, models
from django.core.validators import RegexValidator

import judge.models.problem_data
import judge.utils.problem_data


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0202_offline_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_ai_generated',
            field=models.BooleanField(default=False, help_text='Whenever the source code is marked as AI-generated.', verbose_name='Is AI-generated'),
        ),
        migrations.AddField(
            model_name='submission',
            name='reason_ai_generated',
            field=models.TextField(null=True,blank=True, help_text='The reason that source code is marked as AI-generated.', verbose_name='Reason AI-generated'),
        ),
    ]
