# Generated by Django 2.2.24 on 2022-01-21 04:15

import django.core.validators
from django.db import migrations, models
from django.core.validators import RegexValidator

import judge.models.problem_data
import judge.utils.problem_data


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0204_fix_ai_detector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='is_ai_generated',
            field=models.BooleanField(default=False, help_text='Whether the source code is marked as AI-generated.', verbose_name='Is AI-generated'),
        ),
    ]
