# Generated by Django 2.2.24 on 2022-01-21 04:15

import django.core.validators
from django.db import migrations, models
from django.core.validators import RegexValidator

import judge.models.problem_data
import judge.utils.problem_data


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0205_fix_ai_detectorr'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='show_statement',
            field=models.BooleanField(default=True, help_text='Whether to show the problem statement to users.', verbose_name='Show statement'),
        ),
    ]