# Generated by Django 3.2.25 on 2026-04-08 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0206_show_statement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(
                    db_index=True,
                    max_length=64,
                    unique=True,
                    validators=[django.core.validators.RegexValidator(
                        '^[a-z0-9-]+$',
                        'Exam slug must contain lowercase letters, numbers, and hyphens only.',
                    )],
                    verbose_name='exam slug',
                )),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='exam name')),
                ('expected_count', models.PositiveIntegerField(default=0, verbose_name='expected problems')),
                ('year', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='year')),
                ('exam_type', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='exam type')),
                ('province', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='province')),
                ('status_note', models.CharField(blank=True, max_length=128, verbose_name='status note')),
                ('is_public', models.BooleanField(db_index=True, default=True, verbose_name='public')),
                ('sort_order', models.IntegerField(db_index=True, default=0, verbose_name='sort order')),
            ],
            options={
                'verbose_name': 'exam tag',
                'verbose_name_plural': 'exam tags',
                'ordering': ('-year', 'sort_order', 'name', 'slug'),
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='exam_tags',
            field=models.ManyToManyField(
                blank=True,
                help_text='Attach this problem to one or more exam progress tags.',
                related_name='problems',
                to='judge.ExamTag',
                verbose_name='exam tags',
            ),
        ),
    ]
