# Generated by Django 3.2.25 on 2026-04-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0207_exam_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamProvince',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='province name')),
                ('sort_order', models.IntegerField(db_index=True, default=0, verbose_name='sort order')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'exam province',
                'verbose_name_plural': 'exam provinces',
                'ordering': ('sort_order', 'name'),
            },
        ),
    ]
