# Generated by Django 3.2.25 on 2026-04-08 03:28

from django.db import migrations


def seed_exam_provinces(apps, schema_editor):
    ExamTag = apps.get_model('judge', 'ExamTag')
    ExamProvince = apps.get_model('judge', 'ExamProvince')

    provinces = sorted({
        (value or '').strip()
        for value in ExamTag.objects.exclude(province='').values_list('province', flat=True)
        if (value or '').strip()
    })

    for index, name in enumerate(provinces):
        ExamProvince.objects.get_or_create(
            name=name,
            defaults={'sort_order': index, 'is_active': True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0208_exam_provinces'),
    ]

    operations = [
        migrations.RunPython(seed_exam_provinces, migrations.RunPython.noop),
    ]
