# Generated by Django 3.2.25 on 2026-04-08 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0209_seed_exam_provinces'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='category name')),
                ('sort_order', models.IntegerField(db_index=True, default=0, verbose_name='sort order')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'exam category',
                'verbose_name_plural': 'exam categories',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='examtag',
            name='category',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='exam_tags',
                to='judge.ExamCategory',
                verbose_name='category',
            ),
        ),
    ]
