# Generated by Django 3.2.25 on 2026-04-08 18:10

import django.db.models.deletion
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0210_exam_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTagProblemPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='exam points')),
                ('sort_order', models.IntegerField(db_index=True, default=0, verbose_name='sort order')),
                ('exam_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_points', to='judge.examtag', verbose_name='exam tag')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_point_links', to='judge.problem', verbose_name='problem')),
            ],
            options={
                'verbose_name': 'exam tag problem point',
                'verbose_name_plural': 'exam tag problem points',
                'ordering': ('sort_order', 'problem__code'),
                'unique_together': {('exam_tag', 'problem')},
            },
        ),
    ]
