# Generated by Django 3.2.25 on 2026-04-08 18:16

from django.db import migrations


def seed_exam_tag_problem_points(apps, schema_editor):
    Problem = apps.get_model('judge', 'Problem')
    ExamTagProblemPoint = apps.get_model('judge', 'ExamTagProblemPoint')
    through = Problem.exam_tags.through

    problem_points = dict(Problem.objects.values_list('id', 'points'))
    batch = []
    for exam_tag_id, problem_id in through.objects.values_list('examtag_id', 'problem_id').iterator():
        batch.append(
            ExamTagProblemPoint(
                exam_tag_id=exam_tag_id,
                problem_id=problem_id,
                points=float(problem_points.get(problem_id, 0) or 0),
            ),
        )
        if len(batch) >= 2000:
            ExamTagProblemPoint.objects.bulk_create(batch, ignore_conflicts=True)
            batch = []

    if batch:
        ExamTagProblemPoint.objects.bulk_create(batch, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0211_exam_tag_problem_points'),
    ]

    operations = [
        migrations.RunPython(seed_exam_tag_problem_points, migrations.RunPython.noop),
    ]
