# Generated by Django 3.2.25 on 2026-04-08 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0212_seed_exam_tag_problem_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamUserProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_points', models.FloatField(default=0, verbose_name='earned points')),
                ('total_points', models.FloatField(default=0, verbose_name='total points')),
                ('percent', models.FloatField(default=0, verbose_name='percent')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('exam_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='judge.examtag', verbose_name='exam tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_progress', to='judge.profile', verbose_name='user')),
            ],
            options={
                'verbose_name': 'exam user progress',
                'verbose_name_plural': 'exam user progress',
                'unique_together': {('user', 'exam_tag')},
            },
        ),
    ]
