# Generated by Django 3.2.25 on 2026-04-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0213_exam_user_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtag',
            name='exam_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='exam date'),
        ),
    ]
