# Generated by Django 3.2.25 on 2026-04-21 12:00

from django.contrib.auth.hashers import is_password_usable, make_password
from django.db import migrations
from django.utils.crypto import get_random_string


def set_random_password_for_social_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserSocialAuth = apps.get_model('social_django', 'UserSocialAuth')

    social_user_ids = UserSocialAuth.objects.values_list('user_id', flat=True).distinct()
    users = User.objects.filter(id__in=social_user_ids).only('id', 'password')

    for user in users.iterator():
        if is_password_usable(user.password):
            continue
        user.password = make_password(get_random_string(32))
        user.save(update_fields=['password'])


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0010_uid_db_index'),
        ('judge', '0215_sync_schema_and_add_polygon_import_permission'),
    ]

    operations = [
        migrations.RunPython(set_random_password_for_social_users, migrations.RunPython.noop),
    ]
