# Generated by Django 3.2.25 on 2026-04-26

from django.db import migrations, models


def mark_existing_organizations_paid(apps, schema_editor):
    Organization = apps.get_model('judge', 'Organization')
    Organization.objects.update(plan='P')


def mark_existing_organizations_free(apps, schema_editor):
    Organization = apps.get_model('judge', 'Organization')
    Organization.objects.update(plan='F')


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0216_set_random_password_for_social_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='plan',
            field=models.CharField(
                choices=[('F', 'Free'), ('P', 'Paid')],
                default='F',
                max_length=1,
                verbose_name='organization plan',
            ),
        ),
        migrations.RunPython(mark_existing_organizations_paid, mark_existing_organizations_free),
    ]
