# Generated by Django 3.2.25 on 2026-04-27 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0217_organization_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organizations', to='judge.profile', verbose_name='creator'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['plan', 'is_unlisted', 'name'], name='judge_org_plan_unlist_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['creator', 'plan', '-creation_date'], name='judge_org_creator_plan_idx'),
        ),
    ]
