# Generated by Django 3.2.25 on 2026-09-20 15:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0230_storage_eviction_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtag',
            name='milestone_note',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(4000)], verbose_name='Giải thích chung'),
        ),
        migrations.AddField(
            model_name='examtag',
            name='milestone_score_context',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ngữ cảnh điểm chung'),
        ),
        migrations.AddField(
            model_name='examtag',
            name='milestone_source_note',
            field=models.TextField(blank=True, help_text='Tự ghi nguồn của thông tin, ví dụ link, tên tài liệu hoặc người cung cấp. Chỉ hiển thị cho superadmin trong Django admin; không công khai trên website.', validators=[django.core.validators.MaxLengthValidator(4000)], verbose_name='Ghi chú nguồn (nội bộ)'),
        ),
        migrations.CreateModel(
            name='ExamScoreMilestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Tên mốc tùy ý, ví dụ Vàng, Top 32, Điểm chuẩn chuyên Tin.', max_length=160, verbose_name='Tên mốc')),
                ('score', models.DecimalField(decimal_places=4, help_text='Điểm theo nguồn, không nhất thiết cùng thang điểm với các bài trên ClueOJ.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Điểm')),
                ('compare_with_practice_score', models.BooleanField(default=False, help_text='Bật khi có thể so trực tiếp điểm luyện tập của đề trên ClueOJ với mốc này. Điểm luyện tập lớn hơn hoặc bằng mốc sẽ được đánh dấu đã đạt. Tắt nếu mốc chỉ cung cấp thông tin, ví dụ tổng điểm xét tuyển gồm nhiều môn.', verbose_name='Tự động đối chiếu với điểm luyện tập')),
                ('score_context', models.CharField(blank=True, max_length=200, verbose_name='Ngữ cảnh điểm riêng')),
                ('note', models.TextField(blank=True, help_text='Với tuyển sinh, ghi rõ tổng xét tuyển và công thức tính điểm.', validators=[django.core.validators.MaxLengthValidator(4000)], verbose_name='Giải thích')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, help_text='Bỏ chọn để tạm ẩn mốc.', verbose_name='Hiển thị')),
                ('exam_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_milestones', to='judge.examtag')),
            ],
            options={
                'verbose_name': 'Mốc điểm tham khảo',
                'verbose_name_plural': 'Mốc điểm tham khảo',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='examscoremilestone',
            constraint=models.CheckConstraint(check=models.Q(('score__gte', 0)), name='exam_milestone_score_nonnegative'),
        ),
    ]
