# Generated by Django 3.2.25 on 2026-09-21 03:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0231_exam_score_milestones'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgingUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_id', models.PositiveIntegerField(db_index=True)),
                ('problem_id', models.PositiveIntegerField()),
                ('problem_code', models.CharField(max_length=128)),
                ('organization_id', models.PositiveIntegerField(null=True)),
                ('organization_name', models.CharField(blank=True, max_length=256)),
                ('judge_name', models.CharField(blank=True, max_length=128)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(null=True)),
                ('usage_date', models.DateField(db_index=True)),
                ('seconds', models.FloatField(default=0)),
                ('is_rejudge', models.BooleanField(default=False)),
                ('state', models.CharField(default='P', max_length=2)),
                ('case_times', models.JSONField(default=dict)),
            ],
        ),
        migrations.AddIndex(
            model_name='judgingusage',
            index=models.Index(fields=['organization_id', 'usage_date'], name='judging_org_date'),
        ),
        migrations.AddIndex(
            model_name='judgingusage',
            index=models.Index(fields=['problem_id', 'usage_date'], name='judging_problem_date'),
        ),
    ]
