# Generated by Django 3.2.25 on 2026-09-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0232_judging_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgingUsageDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_key', models.PositiveIntegerField(default=0)),
                ('problem_id', models.PositiveIntegerField()),
                ('organization_name', models.CharField(blank=True, max_length=256)),
                ('problem_code', models.CharField(max_length=128)),
                ('usage_date', models.DateField(db_index=True)),
                ('seconds', models.FloatField(default=0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('rejudges', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddConstraint(
            model_name='judgingusagedaily',
            constraint=models.UniqueConstraint(fields=('organization_key', 'usage_date', 'problem_id'), name='judging_daily_unique'),
        ),
    ]
