# Generated by Django 3.2.25 on 2026-09-21 03:36

from django.db import migrations, models, transaction


def combine_daily_rows(apps, schema_editor):
    Daily = apps.get_model('judge', 'JudgingUsageDaily')
    alias = schema_editor.connection.alias
    rows = list(Daily.objects.using(alias).values('organization_key', 'usage_date').annotate(
        organization_name=models.Max('organization_name'), seconds=models.Sum('seconds'),
        attempts=models.Sum('attempts'), rejudges=models.Sum('rejudges'),
    ).order_by())
    with transaction.atomic(using=alias):
        Daily.objects.using(alias).all().delete()
        Daily.objects.using(alias).bulk_create([
            Daily(problem_id=0, problem_code='', **row) for row in rows
        ], batch_size=2000)


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0233_judging_usage_daily'),
    ]

    operations = [
        migrations.RunPython(combine_daily_rows),
        migrations.RemoveConstraint(
            model_name='judgingusagedaily',
            name='judging_daily_unique',
        ),
        migrations.RemoveField(
            model_name='judgingusagedaily',
            name='problem_code',
        ),
        migrations.RemoveField(
            model_name='judgingusagedaily',
            name='problem_id',
        ),
        migrations.AddConstraint(
            model_name='judgingusagedaily',
            constraint=models.UniqueConstraint(fields=('organization_key', 'usage_date'), name='judging_daily_unique'),
        ),
    ]
