# Generated by Django 3.2.25 on 2026-09-21 14:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0232_squashed_0235_judging_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamOfflineAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=200)),
                ('started_at', models.DateTimeField()),
                ('deadline', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, max_length=16)),
                ('active_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_offline_attempt', to='judge.profile')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ExamOfflineAttemptProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField()),
                ('partial', models.BooleanField()),
                ('sort_order', models.PositiveIntegerField()),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='judge.examofflineattempt')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='examtag',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='examtag',
            name='virtual_offline_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='offline_hidden',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='ExamOfflineSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='judge.examofflineattemptproblem')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='offline_entry', to='judge.submission')),
            ],
        ),
        migrations.AddField(
            model_name='examofflineattemptproblem',
            name='final_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='judge.submission'),
        ),
        migrations.AddField(
            model_name='examofflineattemptproblem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='judge.problem'),
        ),
        migrations.AddField(
            model_name='examofflineattempt',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offline_attempts', to='judge.examtag'),
        ),
        migrations.AddField(
            model_name='examofflineattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offline_attempts', to='judge.profile'),
        ),
        migrations.AddConstraint(
            model_name='examofflineattemptproblem',
            constraint=models.UniqueConstraint(fields=('attempt', 'problem'), name='offline_attempt_problem_unique'),
        ),
        migrations.AddIndex(
            model_name='examofflineattempt',
            index=models.Index(fields=['user', 'exam', '-id'], name='offline_user_exam_idx'),
        ),
    ]
