# Generated by Django 3.2.25 on 2026-09-23 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0242_organization_temporary_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreakSummary',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='judge.profile')),
                ('timezone', models.CharField(max_length=50)),
                ('last_day', models.DateField(null=True)),
                ('current_length', models.PositiveIntegerField(default=0)),
                ('longest', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StreakRebuildRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('user', 'User'), ('problem', 'Problem')], max_length=10)),
                ('object_id', models.PositiveIntegerField()),
                ('cursor', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('kind', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='StreakProblemState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.PositiveIntegerField()),
                ('pending', models.BooleanField(default=True)),
                ('rebuild', models.BooleanField(default=True)),
                ('dirty_date', models.DateTimeField(null=True)),
                ('dirty_id', models.PositiveIntegerField(null=True)),
                ('last_date', models.DateTimeField(null=True)),
                ('last_id', models.PositiveIntegerField(default=0)),
                ('best_points', models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ('solved', models.BooleanField(default=False)),
                ('retry_at', models.DateTimeField(null=True)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.profile')),
            ],
        ),
        migrations.CreateModel(
            name='StreakDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.profile')),
            ],
        ),
        migrations.CreateModel(
            name='StreakContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.PositiveIntegerField()),
                ('submission_id', models.PositiveIntegerField(unique=True)),
                ('day', models.DateField()),
                ('previous_points', models.DecimalField(decimal_places=3, max_digits=20)),
                ('points', models.DecimalField(decimal_places=3, max_digits=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.profile')),
            ],
        ),
        migrations.CreateModel(
            name='StreakRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('length', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.profile')),
            ],
            options={
                'unique_together': {('user', 'start')},
            },
        ),
        migrations.AddIndex(
            model_name='streakproblemstate',
            index=models.Index(fields=['pending', 'retry_at', 'id'], name='streak_pending_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='streakproblemstate',
            unique_together={('user', 'problem_id')},
        ),
        migrations.AlterUniqueTogether(
            name='streakday',
            unique_together={('user', 'day')},
        ),
        migrations.AddIndex(
            model_name='streakcontribution',
            index=models.Index(fields=['user', 'day'], name='streak_contrib_day_idx'),
        ),
        migrations.AddIndex(
            model_name='streakcontribution',
            index=models.Index(fields=['user', 'problem_id'], name='streak_contrib_pair_idx'),
        ),
    ]
